
#cmakedefine LUGDULOV_VERSION		"@LUGDULOV_VERSION@"
#cmakedefine HAVE_QT_LOCATION
#cmakedefine HAVE_QT_BEARER
#cmakedefine BUILD_STATIC_PLUGINS
#cmakedefine PLUGINS_INSTALL_DIR	"@PLUGINS_INSTALL_DIR@"
#cmakedefine PLUGINS_EXTEND_DIR		"@PLUGINS_EXTEND_DIR@"
#cmakedefine Q_WS_MAEMO_5
#cmakedefine USE_QMAPCONTROL