# 
# Do not Edit! Generated by:
# spectacle version 0.18
# 
# >> macros
# << macros

Name:       lugdulov
Summary:    Lugdulo'V - Find a bike in your City
Version:    0.4.0
Release:    1
Group:      Applications/Productivity
License:    GPLv2
URL:        http://xf.iksaif.net/dev/lugdulov.html
Source0:    %{name}-%{version}.tar.bz2
Source100:  lugdulov.yaml
BuildRequires:  pkgconfig(QtCore) >= 4.6.0
BuildRequires:  pkgconfig(QtNetwork)
BuildRequires:  pkgconfig(QtGui)
BuildRequires:  pkgconfig(QJson)
BuildRequires:  qt-mobility-devel
BuildRequires:  cmake


%description
Find a bike quickly in your city, with map and geolocalisation support !



%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre
mkdir meego-build
cd meego-build
cmake ..  \
    -DCMAKE_INSTALL_PREFIX:PATH=%{_prefix} \
    -DLUGDULOV_FULL_UI=ON


make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
cd meego-build
%make_install 

# >> install post
# << install post


%post
/bin/touch --no-create %{_datadir}/icons/hicolor || :
%{_bindir}/gtk-update-icon-cache \
  --quiet %{_datadir}/icons/hicolor 2> /dev/null|| :
update-desktop-database %{_datadir}/applications &> /dev/null || :

%postun
/bin/touch --no-create %{_datadir}/icons/hicolor || :
%{_bindir}/gtk-update-icon-cache \
  --quiet %{_datadir}/icons/hicolor 2> /dev/null|| :
update-desktop-database %{_datadir}/applications &> /dev/null || :


%files
%defattr(-,root,root,-)
# >> files
# << files
/usr/bin/lugdulov
/usr/lib/lugdulov/plugins/libstationsaustralia.so
/usr/lib/lugdulov/plugins/libstationsaustria.so
/usr/lib/lugdulov/plugins/libstationsbelgium.so
/usr/lib/lugdulov/plugins/libstationscanada.so
/usr/lib/lugdulov/plugins/libstationsfrance.so
/usr/lib/lugdulov/plugins/libstationsgermany.so
/usr/lib/lugdulov/plugins/libstationsireland.so
/usr/lib/lugdulov/plugins/libstationsjapan.so
/usr/lib/lugdulov/plugins/libstationslatvia.so
/usr/lib/lugdulov/plugins/libstationslower-austria.so
/usr/lib/lugdulov/plugins/libstationsluxembourg.so
/usr/lib/lugdulov/plugins/libstationsnew-zealand.so
/usr/lib/lugdulov/plugins/libstationsspain.so
/usr/lib/lugdulov/plugins/libstationsswitzerland.so
/usr/lib/lugdulov/plugins/libstationsunited-kingdom.so
/usr/lib/lugdulov/plugins/libstationsusa.so
/usr/share/applications/lugdulov.desktop
/usr/share/icons/hicolor/64x64/apps/lugdulov.png
/usr/share/icons/hicolor/scalable/apps/lugdulov.svg
