#!/bin/sh

if [ "$BASH_SOURCE" == "$0" ];then
  BUNDLE=`echo "$0" | sed -e 's/\/Contents\/MacOS\/.*//'`
else
  BUNDLE=`echo "$BASH_SOURCE" | sed -e 's/\/Contents\/MacOS\/.*//'`
fi
RESOURCES=${BUNDLE}/Contents/Resources

echo "BUNDLE: ${BUNDLE}"
echo "RESOURCES: ${RESOURCES}"

export PATH="${RESOURCES}/bin:$PATH"

if [ "${DYLD_LIBRARY_PATH+set}" = "set" ]; then
    export DYLD_LIBRARY_PATH="${RESOURCES}/lib/:${DYLD_LIBRARY_PATH}"
else
    export DYLD_LIBRARY_PATH="${RESOURCES}/lib/"
fi

exec "${RESOURCES}/bin/lugdulov" "$@"
